### ISSUE TITLE
关于css未能引入的问题

### ISSUE THREAD

**Issue by leeir** [TongchengQiu/Slider-React#2]
请问你的css引入为何不起效果？

require('./Slider.scss');

查看元素样式并没有，什么原因

**Comment by leeir** [comment]
样式问题已然解决  我换了一种方式来引入  用了classnames     ，但是还有个问题咨询下
就是
    this.setState({nowLocal: _n});
这一句的问题  报了这么个错
warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

**Comment by leeir** [comment]
已然解决    非常感谢  原来原因出在了给元素添加click事件的时候并没有做bind(this, ...) 
导致了它自动执行了  然后就是卡在了每次都是调用turn，然后就改变state 然后就rerender ，然后就没有然后了  死循环去了 ！这问题纠结死我了  总算圆满解决了！

**Comment by TongchengQiu** [comment]
能好用就好啦～
